apiVersion: v1
kind: Service
metadata:
  name: assignment-go-service
spec:
  selector:
    app: assignment-go
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePorts: 30000
